- Detect ContainerDevice SSH capabilities - Automatically Deploy SSH key to device - Refactored the key generation to make sure its only running once

diff --git a/share/qtcreator/ubuntu/scripts/openssh_publickey_create b/share/qtcreator/ubuntu/scripts/openssh_publickey_create
--- a/share/qtcreator/ubuntu/scripts/openssh_publickey_create
+++ b/share/qtcreator/ubuntu/scripts/openssh_publickey_create
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright 2013 Canonical Ltd.
+# Copyright 2016 Canonical Ltd.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
@@ -14,17 +14,18 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>
+# Author: Benjamin Zeller <benjamin.zeller@canonical.com>
 
-. `dirname $0`/functions.inc
-
-USERNAME=$2
-MIN_KEYLEN="2048"
-
-if [ -z "$USERNAME" ]; then
-    echo "Username missing"
-    echo "Usage: openssh_publickey <deviceId> <username>"
+if [ -z "$USDK_CONF_DIR" ]; then
+    echo "USDK_CONF_DIR must be set in order for this scripts to work" 
     exit 1
+else
+    CONFIGDIR=$USDK_CONF_DIR
 fi
+
+SSHIDENTITY=${CONFIGDIR}/ubuntudevice_id_rsa
+
+MIN_KEYLEN="2048"
 
 function check_key {
     printf "Checking keylen.."
@@ -34,41 +35,7 @@ function check_key {
         echo "SSH key len ${KEY_LEN} is too weak. Creating a new one"
         generate_key
         deploy_key
-    else
-        echo "Checking for keys.."
-        KEY=`cat $SSHIDENTITY.pub`
-        set +e
-        PHABLET_KEYS=`adb_shell "cat /home/$USERNAME/.ssh/authorized_keys2"`
-        KEYS=`echo $PHABLET_KEYS | grep "$KEY"`
-        set -e
-        echo
-        echo "Host key is:"
-        echo $KEY
-        echo
-        echo "We have following keys on the device: "
-        echo $KEYS
-        if [[ -z $KEYS || $KEYS == *No\ such* ]]; then
-            echo "*no keys*"
-            echo
-            deploy_key
-        else
-            echo
-            echo "The host key has been already deployed."
-        fi
     fi
-}
-
-function deploy_key {
-    echo "Deploy the host key to the device.."
-    KEY=`cat $SSHIDENTITY.pub`
-    adb_shell "mkdir -p /home/$USERNAME/.ssh"
-    echo "..key folder created!"
-    adb_shell "echo $KEY >> /home/$USERNAME/.ssh/authorized_keys2"
-    echo "..key deployed!"
-    adb_shell "chown -R $USERNAME:$USERNAME /home/$USERNAME/.ssh"
-    adb_shell "chmod 0700 /home/$USERNAME/.ssh"
-    adb_shell "chmod 0600 /home/$USERNAME/.ssh/authorized_keys2"
-    echo "..permissions updated!"
 }
 
 function generate_key {
@@ -82,9 +49,11 @@ function generate_key {
 
 #################
 
+exec {lock_fd}>${CONFIGDIR}/.keylock || exit 1
+flock -x -w 10 "$lock_fd" || { echo "ERROR: flock() failed." >&2; exit 1; }
+
 if [[ -f $SSHIDENTITY ]]; then
   check_key
 else
   generate_key
-  deploy_key
 fi
