catch errors from pkcon

diff --git a/share/qtcreator/ubuntu/scripts/qtc_project_click_deploy b/share/qtcreator/ubuntu/scripts/qtc_project_click_deploy
--- a/share/qtcreator/ubuntu/scripts/qtc_project_click_deploy
+++ b/share/qtcreator/ubuntu/scripts/qtc_project_click_deploy
@@ -80,6 +80,15 @@ for FILE in $FILES;
 do
  echo "Installing $FILE to device.."
  # note adb shell and adb_shell are two different things, adb_shell comes from functions.inc
- adb_shell sudo -H -u ${TARGET_DEVICE_USERNAME} pkcon install-local --allow-untrusted ${TARGET_DEVICE_HOME}/${FILE}
+ LOG="$(mktemp)"
+ adb_shell sudo -H -u ${TARGET_DEVICE_USERNAME} pkcon -p install-local --allow-untrusted ${TARGET_DEVICE_HOME}/${FILE} 2>&1 | tee $LOG
+ # adb shell does not return the exit code of what was run which is horrible
+ # (https://code.google.com/p/android/issues/detail?id=3254)
+ if grep "^Fatal error:" $LOG; then
+     echo "pkcon failed"
+     rm -f $LOG
+     exit 1;
+ fi
+ rm -rf $LOG
 done
 echo "All files installed succesfully"
