- Fixes Bug lp:1488085 "Navigating in the Add Security Policies window is broken with keyboard" - Fixes Bug lp:1489344 "Install on device is broken" - Fixes Bug lp:1489567 "Ubuntu gallery can not be openend"

diff --git a/share/qtcreator/ubuntu/scripts/qtc_launch_gallery b/share/qtcreator/ubuntu/scripts/qtc_launch_gallery
--- a/share/qtcreator/ubuntu/scripts/qtc_launch_gallery
+++ b/share/qtcreator/ubuntu/scripts/qtc_launch_gallery
@@ -15,9 +15,23 @@
 #
 # Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>
 
-echo "Copying ubuntu-ui-toolkit-gallery from /usr/lib/ubuntu-ui-toolkit/examples to /tmp"
+EXAMPLES_PATH="/usr/lib/ubuntu-ui-toolkit/examples"
+NEW_EXAMPLES_PATH="$(qmake -query QT_INSTALL_EXAMPLES)/ubuntu-ui-toolkit/examples"
+
+if [ -d "${NEW_EXAMPLES_PATH}" ]
+then
+    EXAMPLES_PATH=${NEW_EXAMPLES_PATH}
+else
+    if [ ! -d "${EXAMPLES_PATH}" ]
+    then
+        echo "Could not find the ubuntu-ui-toolkit examples, please make sure they are installed"
+        exit 1
+    fi
+fi
+
+echo "Copying ubuntu-ui-toolkit-gallery from ${EXAMPLES_PATH} to /tmp"
 mkdir -p /tmp/ubuntu-ui-toolkit-gallery
-cp -r /usr/lib/ubuntu-ui-toolkit/examples/ubuntu-ui-toolkit-gallery/* /tmp/ubuntu-ui-toolkit-gallery
+cp -r "${EXAMPLES_PATH}/ubuntu-ui-toolkit-gallery/*" /tmp/ubuntu-ui-toolkit-gallery
 echo "Opening project in Qt Creator"
 qtcreator -client /tmp/ubuntu-ui-toolkit-gallery/ubuntu-ui-toolkit-gallery.qmlproject &
 echo "Launching the qmlscene"
